### ISSUE TITLE
Lamer binary in next release ?

### ISSUE THREAD

**Issue by GitHubRulesOK** [marmayogi/TTF2PostscriptCID-Win#1]
many windows users may have little experience using compilers so expect prebuilt binaries, especialy portable and single exe without dependencies, yes we are either underpowered or lazy builders if not consumers :-)

**Comment by marmayogi** [comment]
A stand-alone binary **ttf2postscriptcid.exe** has been added into repository and a new `Release v3.0` has been published. This will avoid the need to build sources using Visual Studio.
